version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.30
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.30
    - 1.4.31
